variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

stages:
    - deploy
    - status

build:
    image: pypywheels/manylinux2010-pypy_x86_64
    stage: deploy
    before_script:
        - yum -y -q update
        - yum install -y -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - yum -y -q groupinstall "Development Tools"
        - yum -y -q --enablerepo=extras install epel-release
        - yum install -y -q bison flex git
        - yum install -y -q python34
        - alias python3=python34
        - yum install -y -q python34-devel
        - wget https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip.py install
        # - yum install -y -q python34-pip
        - yum install -y -q automake autoconf pcre-devel
        - python3 -m pip install -U pip
        - python3 -m pip install -U setuptools wheel twine
        - python3 -m pip install -U anybadge
        - git clone https://github.com/swig/swig.git
        - cd swig
        - git checkout rel-4.0.0
        - ./autogen.sh
        - ./configure
        - make
        - make install
        - cd ..
    script:
        - python3 setup.py sdist bdist_wheel
        - if twine upload dist/*.tar.gz --verbose && twine upload dist/*.whl --verbose; then echo "PASSED JOB" && anybadge --label=pipeline --value=passing --file=build.svg passing=green failing=red; else echo "FAILED JOB" && anybadge --label=pipeline --value=failing --file=build.svg passing=green failing=red; fi
        - mkdir -p public; mv build.svg public/build.svg
    artifacts:
        paths:
            - public/
            - build/
            - dist/
            - libcolgraph.egg-info/
            - setup.py
    only:
        changes:
            - .pipeline.trigger
    allow_failure: true
    environment:
        name: dev

pages:
    stage: status
    dependencies:
        - build
    script:
        - mkdir -p public
    artifacts:
        paths:
            - public/
    only:
        changes:
            - .pipeline.trigger
